import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case chinese = "zh-Hans"
    case english = "en"
    var id: String { rawValue }
    var name: String { self == .chinese ? "简体中文" : "English" }
    static let defaultsKey = "appLanguage.v1"
    static var current = load()
    static func load(from defaults: UserDefaults = .standard) -> Self {
        Self(rawValue: defaults.string(forKey: defaultsKey) ?? "") ?? .chinese
    }
    func save(to defaults: UserDefaults = .standard) { defaults.set(rawValue, forKey: Self.defaultsKey) }
}

func L(_ key: String, _ arguments: CVarArg...) -> String {
    let format = AppLanguage.current == .english ? Localization.english[key] ?? key : key
    return arguments.isEmpty ? format : String(format: format, locale: Locale(identifier: AppLanguage.current.rawValue), arguments: arguments)
}

enum Localization {
    static let english: [String: String] = [
        "语言": "Language",
        "开机自动运行": "Launch at Login",
        "进入 Mac 桌面后在后台运行，不弹出主窗口。": "Run in the background when you log in to your Mac, without opening the main window.",
        "请在系统设置中允许 Renamer 自动运行。": "Allow Renamer to launch at login in System Settings.",
        "自动运行设置失败：%@": "Could not change launch at login: %@",
        "给桌面一个名字": "Give your desktops a name",
        "按名字找到你的工作、音乐与游戏空间。": "Find your spaces for work, music, and play by name.",
        "技术预览 %@": "Preview %@",
        "为这个桌面命名": "Name this desktop",
        "当前桌面": "Current desktop",
        "桌面 %d": "Desktop %d",
        "全屏空间 %d": "Full-screen space %d",
        "保存": "Save",
        "切换到这个桌面": "Switch to this desktop",
        "先允许辅助功能": "Allow Accessibility access",
        "用于读取 Mission Control 和选择桌面。你可以先编辑名称。": "Required to read Mission Control and switch desktops. You can edit names now.",
        "打开设置": "Open Settings",
        "屏幕": "Display",
        "%d 个桌面": "%d desktops",
        "暂未读取到桌面，请在菜单栏选择“刷新桌面与名称显示”。": "No desktops found. Choose Refresh Desktops and Labels in the menu bar.",
        "已保留 %d 条未匹配名称，可能来自已断开的屏幕或旧桌面；不会自动分配给其他桌面。": "%d unmatched names have been kept for disconnected displays or old desktops. They won't be assigned to other desktops.",
        "缩略图名称": "Thumbnail labels",
        "%@ · %d 号字": "%@ · %d pt",
        "调整颜色、位置和大小…": "Colors, Position & Size…",
        "在空白区域显示当前桌面名称": "Show current name below thumbnails",
        "单独设置外观与位置…": "Appearance & Position…",
        "独立设置大小和颜色；关闭后，顶部缩略图名称仍会显示。": "Separate size and colors. Thumbnail labels remain visible when this is off.",
        "搜索快捷键": "Search shortcut",
        "启用桌面搜索": "Enable desktop search",
        "点击后按下新的快捷键；按 Esc 取消": "Click and press a new shortcut. Esc cancels.",
        "预览名称": "Preview Labels",
        "搜索桌面": "Search Desktops",
        "桌面菜单": "Desktop Menu",
        "退出 Renamer": "Quit Renamer",
        "缩略图名称外观": "Thumbnail Label Appearance",
        "只调整顶部缩略图名称，设置自动保存。": "Changes apply to thumbnail labels and save automatically.",
        "桌面缩略图预览": "Desktop thumbnail preview",
        "背景颜色": "Background color",
        "字体颜色": "Text color",
        "自动选择字体颜色": "Choose text color automatically",
        "缩略图内的位置": "Position in thumbnail",
        "位置": "Position",
        "大小": "Size",
        "名称框大小": "Label size",
        "文字与底框一起调整，宽度随名称自动适配。": "Resizes the text and background. Width adjusts to the name.",
        "位置设置用于展开的桌面缩略图；顶部收起时仍对齐系统标题。": "Position applies to expanded thumbnails. Collapsed labels align with system titles.",
        "恢复默认外观": "Reset Appearance",
        "完成": "Done",
        "当前桌面名称": "Current Desktop Label",
        "与顶部缩略图分开设置，调整后自动保存。": "Independent of thumbnail labels. Changes save automatically.",
        "当前桌面名称大小": "Current desktop label size",
        "%d 号": "%d pt",
        "放到空白处": "Place in an open area",
        "默认在画面下方。点击或拖动下面的示意图，选择适合你窗口排列的位置。": "Defaults to the bottom. Click or drag in the diagram to choose a position that suits your windows.",
        "名称": "Name",
        "当前名称位置示意图；也可使用下方滑块调整": "Label position diagram. You can also use the sliders below.",
        "左右": "Horizontal",
        "上下": "Vertical",
        "名称左右位置": "Horizontal label position",
        "名称上下位置": "Vertical label position",
        "位置按屏幕比例保存，会避开顶部缩略图区域；窗口排列变化后可再次调整。": "Position scales with the display and avoids the thumbnail strip. Adjust it when your window layout changes.",
        "恢复当前名称默认外观": "Reset Current Label",
        "输入桌面名称…": "Type a desktop name…",
        "%@ · 桌面 %d": "%@ · Desktop %d",
        "没有匹配的桌面": "No matching desktops",
        "↑ ↓ 选择    ↵ 切换": "↑ ↓ Select    ↵ Switch",
        "请先允许辅助功能，再按名称切换": "Allow Accessibility access to switch by name",
        "上方": "Top", "居中": "Center", "下方": "Bottom",
        "白色": "White", "灰色": "Gray", "黑色": "Black", "靛蓝": "Indigo",
        "湖蓝": "Ocean", "紫色": "Purple", "珊瑚": "Coral", "金黄": "Gold", "浅白": "Off-white",
        "调整%@": "Adjust %@", "在此处调整%@": "Adjust %@ here",
        "颜色区域；可用下方色调、饱和度和亮度滑块调整": "Color area. Use the hue, saturation, and brightness sliders below.",
        "色调": "Hue", "饱和度": "Saturation", "亮度": "Brightness", "色值": "Hex",
        "十六进制颜色": "Hex color", "应用": "Apply",
        "请输入六位色值，例如 #3478F6": "Enter six hex digits, such as #3478F6",
        "调整后自动保存": "Changes save automatically",
        "键 %d": "Key %d",
        "请按组合键…（Esc 取消）": "Press keys… (Esc cancels)",
        "正在录入 %@，按 Esc 取消": "Recording %@. Esc cancels.",
        "点击后直接按下新的快捷键": "Click, then press a new shortcut",
        "快捷键无法注册，可能已被占用。请点击快捷键重新设置。": "This shortcut could not be registered. It may be in use. Click to set another.",
        "请搭配 ⌘、⌥、⌃ 中的至少一个键，或使用 F1–F20。Esc 取消。": "Include ⌘, ⌥, or ⌃, or use F1–F20. Esc cancels.",
        "这个快捷键无法注册，可能已被占用，请换一个。Esc 取消并保留原设置。": "This shortcut could not be registered. Try another, or press Esc to keep the previous one.",
        "回车或点到别处保存，Esc 取消；留空恢复默认名称": "Return or click away to save. Esc cancels. Leave empty for the default name.",
        "切换到 %@": "Switch to %@", "切换到 %@%@": "Switch to %@%@",
        "（当前桌面）": " (current desktop)", "桌面 %d 名称": "Desktop %d name",
        "保存名称": "Save Name", "重命名": "Rename", "重命名 %@": "Rename %@",
        "Renamer 桌面菜单": "Renamer Desktop Menu",
        "Renamer，当前桌面：%@": "Renamer, current desktop: %@",
        "点击或悬停展开桌面；点名称切换，点铅笔直接编辑": "Click or hover to view desktops. Click a name to switch or a pencil to rename.",
        "%@ · 当前：%@": "%@ · Current: %@", "未识别": "Unknown",
        "暂未读取到桌面，请刷新": "No desktops found. Try refreshing.",
        "需要辅助功能权限…": "Allow Accessibility Access…",
        "搜索桌面…": "Search Desktops…",
        "桌面名称与外观设置…": "Names & Appearance…",
        "刷新桌面与名称显示": "Refresh Desktops and Labels",
        "未能确认切换": "Could not switch", "系统未接受": "The system did not accept",
        "名称文件版本不受支持，已停止写入。": "Unsupported names file version. Saving has been stopped.",
        "名称文件无法读取，原文件已保留：%@": "Unable to read names. The original file has been kept: %@",
        "名称最多 80 个字符。": "Names can contain up to 80 characters.",
        "当前 macOS 的桌面读取接口不可用。": "The desktop interface is unavailable on this version of macOS.",
        "暂时无法读取桌面，已保留名称；请尝试恢复显示。": "Unable to read desktops right now. Names are safe. Try refreshing labels.",
        "桌面数据不完整，暂不更新标签。": "Desktop data is incomplete. Label updates are paused.",
        "屏幕布局正在变化，等待系统稳定后恢复。": "Display layout is changing. Waiting for it to settle.",
        "桌面身份缺失，暂不更新标签。": "A desktop identifier is missing. Label updates are paused.",
        "桌面身份重复，暂不更新标签。": "Duplicate desktop identifiers. Label updates are paused.",
        "桌面 UUID 重复，暂不更新标签。": "Duplicate desktop UUIDs. Label updates are paused.",
        "正在读取桌面…": "Reading desktops…", "名称已保存": "Name saved",
        "已重新读取桌面，等待 Mission Control": "Desktops refreshed. Waiting for Mission Control.",
        "这个桌面已不存在，未保存修改。": "This desktop no longer exists. Changes were not saved.",
        "请先在设置中允许 Renamer 使用辅助功能。": "Allow Accessibility access for Renamer in Settings first.",
        "正在切换，请稍候。": "Switching desktops. Please wait.",
        "目标桌面已不存在或已断开。": "The target desktop no longer exists or its display is disconnected.",
        "已经在 %@": "Already on %@", "正在切换到 %@…": "Switching to %@…",
        "未能确认切换到 %@：快速切换暂不可用。": "Could not switch to %@: fast switching is unavailable.",
        "未能确认切换到 %@。请稍后重试。": "Could not switch to %@. Please try again.",
        "已切换到 %@": "Switched to %@",
        "需要辅助功能权限才能显示标签和切换；名称编辑可用。": "Accessibility access is needed for labels and switching. Name editing is available.",
        "已检测到 Mission Control，但无法定位桌面按钮。请导出诊断。": "Mission Control is open, but desktop buttons could not be located. Export diagnostics for details.",
        "系统未接受桌面切换，请重试（%d）。": "The system did not accept the desktop switch. Try again (%d).",
        "导出失败：%@": "Export failed: %@"
    ]
}
